routes/web.php
<?php

use App\Http\Controllers\AdminController;
use App\Http\Controllers\GameRulesController;
use App\Http\Controllers\ScoresController;
use Illuminate\Support\Facades\Route;

Auth::routes();

Route::get('/players/{game}', 'PlayerController@showPlayers')->name('showPlayers');

//home
Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');
Route::get('/', 'HomeController@index')->name('home')->middleware('auth');

//clock
Route::get('/clock', 'ClockController@showClock')->middleware('auth');
Route::get('/clock/{round_id}', 'ClockController@showClock')->name('showClock')->middleware('auth');


//knockout
//Route::resource('knockout', 'KnockoutController');
Route::get('/game/{game}/knockout/{round}', 'KnockoutController@getKnockoutPlayers')->name('getKnockoutPlayers')->middleware('auth');
//Route::get('/game/{game}/knockout/{round}', 'KnockoutController@getKnockoutPlayers')->name('getKnockoutPlayers')->middleware('auth');
Route::post('/game/{game}/knockout/{round}', 'KnockoutController@storeKnockoutPlayers')->name('storeKnockoutPlayers')->middleware('auth');

//players
Route::resource('game.player', 'PlayerController');
Route::get('player.loginPlayer', 'PlayerController@login')->name('game.player.login');
Route::get('player.gamePlayer', 'PlayerController@selectGame')->name('selectGame');

//rounds
Route::resource('rounds', 'RoundsController')->middleware('auth');
Route::get('/store_round', 'RoundsController@storeRoundForm')->middleware('auth');
route::get('getOneRound/{round}', 'RoundsController@getOneRound')->middleware('auth');
Route::get('/game/{game}/rounds', 'RoundsController@showRounds')->name('showRounds')->middleware('auth');
Route::post('/game/{game}/round', 'RoundsController@storeRound')->name('storeRound')->middleware('auth');
Route::post('/game/{game}/knockout', 'RoundsController@storeKnockoutRound')->name('storeKnockoutRound')->middleware('auth');

//games
Route::resource('game', 'GameController')->middleware('auth');
Route::get('/gameoverview', 'HomeController@index')->middleware('auth');
Route::get('/game/{game}/overview', 'GameController@overview')->name('game.overview')->middleware('auth');

//tables
Route::resource('tables', 'TablesController')->middleware('auth');
Route::get('tables/{table}/player/{player}', 'TablesController@deletePlayer')->name('deletePlayer')->middleware('auth');
Route::get('/admin_tafels_overview', 'AdminController@showAdminTafelsOverview')->middleware('auth');
Route::get('/admin_tafel_toevoegen', 'AdminController@showAdminTafelToevoegen')->middleware('auth');
Route::get('game/{game}/round/{round}/tables', 'TablesController@showTables')->name('showTables')->middleware('auth');
Route::post('/game/{game}/round/{round}/tables', 'TablesController@storeTable')->name('storeTable')->middleware('auth');
Route::get('/game/{game}/tables', 'TablesController@getGameTables')->name('game.tables')->middleware('auth');
Route::post('/game/{game}/table', 'TablesController@store')->name('game.table.store')->middleware('auth');

//scores
Route::resource('scores', 'ScoresController')->middleware('auth');
Route::get('gameScores/{id}', 'ScoresController@showGameScore')->middleware('auth');
Route::get('score/{id}', 'ScoresController@showPlayerScore')->name('showPlayerScore')->middleware('auth');
Route::get('game/{game}/score', 'ScoresController@scoresOverview')->name('scoresOverview')->middleware('auth');
Route::post('/game/{game}/round/{round}/score', 'ScoresController@storeScore')->name('storeScore')->middleware('auth');
Route::post('/player/{game}', 'PlayerController@storePlayer')->name('storePlayer');


//player home


//player scores
Route::get('/player_score', 'ScoresController@showFindPlayerScore')->name('showFindPLayerScore');
Route::post('/player_score', 'ScoresController@findPlayerScore')->name('findPlayerScore');

//GameRules
Route::resource('game.gamerules', 'GameRulesController')->middleware('auth');
Route::get('/gamerule_delete/{gamerule}', 'GameRulesController@destroy')->name('deleteGameRules')->middleware('auth');

//Admin
Route::get('/adminlogin', 'HomeController@adminLogin')->name('adminLogin');

Route::post('/playerLogin', 'PlayerController@login')->name('playerLogin');

app/Http/Controllers/TablesController.php
<?php

namespace App\Http\Controllers;

use App\Game;
use App\Player_games;
use App\Round;
use App\Score;
use App\player;
use App\Table;
use App\table_players;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\View\View;

class TablesController extends Controller
{
    /**
     * @param Round $round
     * @return Factory|View
     */
    public function index(Round $round)
    {
        $tables = Table::where('round_id', '=', $round->id);
        return view('tables.tableoverview', compact('tables', 'game'));
    }

    /**
     * @param Game $game
     * @param Round $round
     * @return Factory|View
     */
    public function showTables(Game $game, Round $round)
    {
        $scores = Score::where('round_id','=',$round->id)->get();
        $tables = Table::where('round_id','=', $round->id)->get();
        foreach ($tables as &$table) {
            $table->players = $table->players()->get();
            $total = 0;
            foreach ($table->players as &$player) {
                $score  = $scores->firstWhere('player_id', $player->id);
                $points = $score ? $score->points : 0;
                $weight = $score ? $score->weight : 0;
                $total += $points;
                $player->setAttribute('points', $points);
                $player->setAttribute('weight', $weight);
            }
            $table->setAttribute('points', $total);
        }
        return view('tables.tableoverview', compact('tables','game', 'round'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @param Game $game
     * @param Round $round
     * @return RedirectResponse
     */
    public function storeTable(Request $request, Game $game, Round $round)
    {
        $max_round = Round::where('game_id', '=', $game->id)->max('id');
        if($max_round != $round->id)
        {
            return back()->with('error','De vorige ronde is nog niet afgelopen!!!');
        }

        $tables = Table::where('round_id', '=', $round->id)->delete();
        $player = Player::where('state', '=', 1)
            ->join('player_games', 'player_games.player_id', '=', 'players.id')
            ->where('player_games.game_id', '=', $game->id)
            ->update(['state' => 0]);

        // gets all players with checked_id=0 for current game_id
        $players = Player::whereRaw('state=0')->where('checked_in','=',1)
            ->join('player_games', 'player_games.player_id', '=', 'players.id')
            ->where('player_games.game_id', '=', $game->id)
            ->orderBy('player_games.weight', 'desc')
            ->inRandomOrder()->get();

        $cnt = count($players);
        $num = 1;
        $plr = 0;

        while ($cnt >= 3) {
            //$tbl = $cnt == 3 || $cnt == 6 || $cnt == 9 ? 3 : 4;
            if ($cnt == 3 || $cnt == 6)
            {
                $tbl = 3;
            }
            elseif ($cnt == 5)
            {
                $tbl = 5;
            }
            else
            {
                $tbl = 4;
            }

            $table = new Table;
            $table->number = $num;
            $table->game_id = $game->id;
            $table->round_id = $round->id;
            $table->user_id = $request->user()->id;
            $table->save();

            for ($i = 0; $i < $tbl; $i++, $plr++) {
                $player = $players[$plr];

                $tp = new table_players;
                $tp->player_id = $player->id;
                $tp->table_id = $table->id;
                $tp->round_id = $round->id;
                $tp->save();

                $player->state = 1;
                $player->save();
            }

            $cnt -= $tbl;
            $num++;

        }
        return back()->with('success','Player added to table successfully!');
    }

    /**
     * @param Game $game
     *
     * @return RedirectResponse
     */
    public function store(Game $game)
    {
        $latestTable = $game->tables()->latest()->first();
        $table = new Table();
        $table->game_id = $game->id;
        $table->user_id = Auth::user()->id;
        if ($latestTable) {
            $number = $latestTable->number + 1;
            $table->number = $number;
            $table->save();
            return back();
        }

        $table->number = 1;
        $table->save();

        return back();
    }

    /**
     * Display the specified resource.
     * @param Table $table
     *
     * @return void
     */
    public function show(Table $table)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     * @param Table $table
     *
     * @return Factory|View
     */
    public function edit(Table $table)
    {
        return view('tables.tableupdate', compact('table'));
    }

    /**
     * Update the specified resource in storage.
     * @param Request $request
     * @param Table $table
     *
     * @return void
     */
    public function update(Request $request, Table $table)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     * @param player $player
     * @param Table $table
     *
     * @return Factory|View
     */
    public function deletePlayer(Player $player, Table $table)
    {
        $player->tables()->detach();
        $player->state = 0;
        $player->save();
        return view('tables.tableupdate', compact('table'))
            ->with('warning','Player deleted from table successfully!');
    }

    /**
     * @param Table $table
     *
     * @return RedirectResponse
     * @throws \Exception
     */
    public function destroy(Table $table)
    {
        $table->players()->update(['state' => 0]);
        $table->delete();
        return back()->with('warning','Table deleted successfully!');
    }

    /**
     * @param Game $game
     *
     * @return Factory|View
     */
    public function getGameTables(Game $game)
    {
        $tables = $game->tables()->get();
        return view('tables.tableList', compact('game', 'tables'));
    }
}

resources/views/tables/tableList.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-1"></div>
            <div class="col-sm-10">
                <div class="row">
                @foreach($tables as $table)
                    <div class="col-2">
                        <div class="card m-3 shadow-lg p-4 bg-white">
                            <div class="card-header">
                                <div class="float-left">
                                    Table: {{$table->number}}
                                </div>
                            </div>
                            <div class="card-body">

                                <div class="btn-group float-right">
                                    <form method="post" action="{{route('tables.destroy', [$table->id])}}">
                                        @csrf
                                        {{method_field('DELETE')}}
                                        <button type="submit" class="btn btn-danger mr-1">delete</button>
                                    </form>
                                    <form method="get" action="{{route('tables.edit', [$table->id])}}">
                                        @csrf
                                        <button type="submit" class="btn btn-primary">edit</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                @endforeach
                </div>
            </div>

            <div class="col-sm-1">
                <form method="post" action="{{route('game.table.store', ['game' => $game->id])}}">
                    @csrf
                    <button type="submit" class="btn btn-primary mr-1">Add new table</button>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/tables/tableoverview.blade.php
@extends('layouts.app')

@section('content')
    @include('components.modalAddRound')
    <div class="container">
        <div class="row">
            <div class="col-1">
                <a href="{{ URL::previous() }}" class="btn btn-primary float-left" role="button">Back</a>
            </div>
            <div class="row col-5">
                <form method="post" action="{{route('storeTable', ['game' => $game->id, 'round' => $round->id])}}">
                    @csrf
                    <input type="submit" class="btn btn-primary m-3" value="Add players to tables randomly">
                </form>
            </div>
            <div class="row col-5 float-left">
                <button type="button" class="btn btn-secondary float-right m-3 shadow" data-toggle="modal"
                        data-target="#modalAddRound">Next Round
                </button>
            </div>
            <div class="col-1"></div>
            @foreach($tables as $table)
                <div class="col-6">
                    <div class="card m-3 shadow-lg p-4 bg-white">
                        <div class="card-header">
                            <div class="float-left">
                                Table: {{$table->number}}
                            </div>
                            <div class="float-right">
                                Total score: {{$table->points}}
                            </div>
                        </div>
                        <div class="card-body">
                            <table class="table">
                                <thead>
                                <tr>
                                    <th scope="col">#</th>
                                    <th scope="col">Name</th>
                                    <th scope="col">Score</th>
                                    <th scope="col">Weight</th>
                                    <th scope="col">Add Score</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($table->players as $player)
                                    <tr>
                                        <th scope="row">{{$player->id}}</th>
                                        <td>{{$player->first_name}}</td>
                                        <td>{{$player->points}}</td>
                                        <td>{{number_format($player->weight, 2)}}</td>
                                        <div class="btn-group float-right">
                                            <td>
                                                <button type="button" class="btn-primary" data-toggle="modal"
                                                        data-target="#myModal{{$player->id}}">+
                                                </button>
                                            </td>
                                            <!-- Modal -->
                                            <div class="modal fade" id="myModal{{$player->id}}" role="dialog">
                                                <div class="modal-dialog">
                                                    <!-- Modal content-->
                                                    <div class="modal-content">
                                                        <div class="modal-header">
                                                            <h4 class="modal-title">Voer de score in</h4>
                                                            <button type="button" class="close" data-dismiss="modal">
                                                                &times;
                                                            </button>
                                                        </div>
                                                        <form method="post"
                                                              action="{{route('storeScore', [$game->id, $round->id])}}">
                                                            @csrf
                                                            <input type="hidden" name="player_id" id="player_id"
                                                                   value="{{$player->id}}">
                                                            <div class="form-group col-md-12">
                                                                <label for="user_code">points</label>
                                                                <input class="form-control" type="number" name="points"
                                                                       required>
                                                            </div>
                                                            <div class="form-group col-md-8 mt-3">
                                                                <input type="submit" class="btn btn-primary"
                                                                       value="Verzend">
                                                            </div>
                                                        </form>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                            <div class="btn-group float-right">
                                <form method="post" action="{{route('tables.destroy', [$table->id])}}">
                                    @csrf
                                    {{method_field('DELETE')}}
                                    <button type="submit" class="btn btn-danger mr-1">delete</button>
                                </form>
                                <form method="get" action="{{route('tables.edit', [$table->id])}}">
                                    @csrf
                                    <button type="submit" class="btn btn-primary">edit</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            @endforeach
        </div>
        <hr>
        <a href="{{ URL::previous() }}" class="btn btn-primary float-left" role="button">Back</a>
    </div>
@endsection

resources/views/tables/tableupdate.blade.php
@extends('layouts.app')

@section('content')
    <table class="table table-bordered col-4" style="margin: 5%">
        <tbody>
        <tr>
            @foreach($table->players as $player)
                <td>
                    <div class="container">
                            <div class="toast-header">
                                <strong class="mr-auto text-primary">{{ $player->code }}</strong>
                                <button type="button" class="ml-2 mb-1 close" data-dismiss="toast"><a href="{{route('deletePlayer', [$player->id, $table->id])}}">&times;</a></button>
                            </div>
                            <div class="toast-body" id="player">
                                <input type="text" class="form-control mt-2" value="{{$player->first_name}}">
                            </div>
                    </div>
                </td>
            @endforeach
{{--            <form method="post" action="{{route('tables.update', [$table->id])}}">--}}
{{--                    @csrf--}}
{{--                    @method('PUT')--}}
{{--                    <td>--}}
{{--                        <input type="submit" class="btn btn-warning" value="update">--}}
{{--                    </td>--}}
{{--                </form>--}}
        </tr>
        </tbody>
    </table>
    <script>
        var x = document.getElementById("player");
        var y = document.getElementById("add");
        $(document).ready(function(){
            $("button").click(function(){
                $(x).replaceWith(function () {
                    return "<input type=\"submit\" class=\"btn btn-danger\" value=\"add\">"
                });
            });
        });
    </script>
@endsection