routes/web.php
<?php

use App\Http\Controllers\AdminController;
use App\Http\Controllers\GameRulesController;
use App\Http\Controllers\ScoresController;
use Illuminate\Support\Facades\Route;

Auth::routes();

Route::get('/players/{game}', 'PlayerController@showPlayers')->name('showPlayers');

//home
Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');
Route::get('/', 'HomeController@index')->name('home')->middleware('auth');

//clock
Route::get('/clock', 'ClockController@showClock')->middleware('auth');
Route::get('/clock/{round_id}', 'ClockController@showClock')->name('showClock')->middleware('auth');


//knockout
//Route::resource('knockout', 'KnockoutController');
Route::get('/game/{game}/knockout/{round}', 'KnockoutController@getKnockoutPlayers')->name('getKnockoutPlayers')->middleware('auth');
//Route::get('/game/{game}/knockout/{round}', 'KnockoutController@getKnockoutPlayers')->name('getKnockoutPlayers')->middleware('auth');
Route::post('/game/{game}/knockout/{round}', 'KnockoutController@storeKnockoutPlayers')->name('storeKnockoutPlayers')->middleware('auth');

//players
Route::resource('game.player', 'PlayerController');
Route::get('player.loginPlayer', 'PlayerController@login')->name('game.player.login');
Route::get('player.gamePlayer', 'PlayerController@selectGame')->name('selectGame');

//rounds
Route::resource('rounds', 'RoundsController')->middleware('auth');
Route::get('/store_round', 'RoundsController@storeRoundForm')->middleware('auth');
route::get('getOneRound/{round}', 'RoundsController@getOneRound')->middleware('auth');
Route::get('/game/{game}/rounds', 'RoundsController@showRounds')->name('showRounds')->middleware('auth');
Route::post('/game/{game}/round', 'RoundsController@storeRound')->name('storeRound')->middleware('auth');
Route::post('/game/{game}/knockout', 'RoundsController@storeKnockoutRound')->name('storeKnockoutRound')->middleware('auth');

//games
Route::resource('game', 'GameController')->middleware('auth');
Route::get('/gameoverview', 'HomeController@index')->middleware('auth');
Route::get('/game/{game}/overview', 'GameController@overview')->name('game.overview')->middleware('auth');

//tables
Route::resource('tables', 'TablesController')->middleware('auth');
Route::get('tables/{table}/player/{player}', 'TablesController@deletePlayer')->name('deletePlayer')->middleware('auth');
Route::get('/admin_tafels_overview', 'AdminController@showAdminTafelsOverview')->middleware('auth');
Route::get('/admin_tafel_toevoegen', 'AdminController@showAdminTafelToevoegen')->middleware('auth');
Route::get('game/{game}/round/{round}/tables', 'TablesController@showTables')->name('showTables')->middleware('auth');
Route::post('/game/{game}/round/{round}/tables', 'TablesController@storeTable')->name('storeTable')->middleware('auth');
Route::get('/game/{game}/tables', 'TablesController@getGameTables')->name('game.tables')->middleware('auth');
Route::post('/game/{game}/table', 'TablesController@store')->name('game.table.store')->middleware('auth');

//scores
Route::resource('scores', 'ScoresController')->middleware('auth');
Route::get('gameScores/{id}', 'ScoresController@showGameScore')->middleware('auth');
Route::get('score/{id}', 'ScoresController@showPlayerScore')->name('showPlayerScore')->middleware('auth');
Route::get('game/{game}/score', 'ScoresController@scoresOverview')->name('scoresOverview')->middleware('auth');
Route::post('/game/{game}/round/{round}/score', 'ScoresController@storeScore')->name('storeScore')->middleware('auth');
Route::post('/player/{game}', 'PlayerController@storePlayer')->name('storePlayer');


//player home


//player scores
Route::get('/player_score', 'ScoresController@showFindPlayerScore')->name('showFindPLayerScore');
Route::post('/player_score', 'ScoresController@findPlayerScore')->name('findPlayerScore');

//GameRules
Route::resource('game.gamerules', 'GameRulesController')->middleware('auth');
Route::get('/gamerule_delete/{gamerule}', 'GameRulesController@destroy')->name('deleteGameRules')->middleware('auth');

//Admin
Route::get('/adminlogin', 'HomeController@adminLogin')->name('adminLogin');

Route::post('/playerLogin', 'PlayerController@login')->name('playerLogin');

app/GameRule.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class GameRule extends Model
{
    /**
     * @return BelongsTo
     */
    public function game()
    {
        return $this->belongsTo(Game::class, 'game_id');
    }
}

app/Http/Controllers/GameRulesController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateGameRuleRequest;
use App\Game;
use App\GameRule;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Redirector;
use Illuminate\View\View;

class GameRulesController extends Controller
{
    /**
     * @param Game $game
     *
     * @return Factory|View
     */
    public function index(Game $game)
    {
       $gamerules = $game->gameRules()->first();

        return view('gamerules.index', compact('gamerules', 'game'));
    }

    /**
     * @param Game $game
     * @return Factory|View
     */
    public function create(Game $game)
    {
        return view('gamerules.create', compact('game'));
    }

    /**
     * @param Game $game
     * @param Request $request
     * @return RedirectResponse|Redirector
     */
    public function store(Game $game, Request $request)
    {
        $gamerule = new GameRule();
        $gamerule->max_players = $request->get('max_players');
        $gamerule->min_players = $request->get('min_players');
        $gamerule->max_rounds = $request->get('max_rounds');
        $gamerule->knockout_phase = $request->get('knockout_phase');
        $gamerule->user_id = $request->user()->id;
        $gamerule->game_id = $game->id;

        $gamerule->save();

        return redirect()->route('game.overview', ['game' => $game->id])->with('success','Gamerule created successfully!');
    }

    /**
     * @param Game $game
     * @param GameRule $gameRule
     *
     * @return Factory|View
     */
    public function show(Game $game, GameRule $gameRule)
    {
        return view('gamerules.show', compact('game', 'gameRule'));
    }

    /**
     * @param Game $game
     * @param $gamerule_id
     *
     * @return Factory|View
     */
    public function edit(Game $game, $gamerule_id)
    {
        $gameRule = GameRule::find($gamerule_id);
        return view('gamerules.edit', compact('game', 'gameRule'));
    }

    /**
     * @param Request $request
     * @param Game $game
     * @param GameRule $gamerule
     *
     * @return RedirectResponse|Redirector
     */
    public function update(Request $request, Game $game, GameRule $gamerule)
    {
        $gamerule->max_players = $request->get('max_players');
        $gamerule->min_players = $request->get('min_players');
        $gamerule->max_rounds = $request->get('max_rounds');
        $gamerule->knockout_phase = $request->get('knockout_phase');
        $gamerule->user_id = $request->user()->id;
        $gamerule->game_id = $game->id;

        $gamerule->save();

        return redirect()->route('game.overview', ['game' => $game->id])->with('info','Gamerule updated successfully!');
    }
}

resources/views/gamerules/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="row h-100">
        <div class="col-sm-2"></div>
        <div class="col-sm-8">
            <h1>Add New Game Rules</h1><hr>
            <div class="row h-100">
                <div class="col-sm-8">
                    <form method='post' action={{route('game.gamerules.store', ['game' => $game->id])}} enctype="multipart/form-data">
                        @csrf
                        <div class="form-group">
                            <label for="name">Max Players:</label>
                            <input name="max_players" type="number" class="form-control" id="name" required="required"/>
                        </div>
                        <div class="form-group">
                            <label for="name">Min Players:</label>
                            <input name="min_players" type="number" class="form-control" id="name" required="required"/>
                        </div>
                        <div class="form-group">
                            <label for="name">Amount of player for the Knockout Phase:</label>
                            <input name="knockout_phase" type="number" class="form-control" id="name" required="required" />
                        </div>
                        <div class="form-group">
                            <label for="name">Max Rounds:</label>
                            <input name="max_rounds" type="number" class="form-control" id="name" required="required"/>
                        </div>
                        <br>
                        <button type="submit" class="btn btn-primary float-right">Add</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-sm-2"></div>
    </div>
@endsection

resources/views/gamerules/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="row h-100">
        <div class="col-sm-2"></div>
        <div class="col-sm-9">
            <h1>Game Rule Edit</h1><hr>
            <div class="row">
                <div class="col-sm-2"></div>
                <div class="col-sm-8">
                    <div class="card w-100">
                        <div class="card-body">
                            <form method='post' action="{{route('game.gamerules.update', ['game' => $game->id, 'gamerule' => $gameRule->id])}}" enctype="multipart/form-data">
                                @csrf
                                @method('PUT')

                                <div class="form-group1">
                                    <label for="name"><h10>Max Players:</h10></label>
                                    <input type="number" class="form-control" name="max_players" id="name" required="required"
                                           value="{{$gameRule->max_players}}"/>
                                </div><br>

                                <div class="form-group1">
                                    <label for="name"><h10>Min PLayers:</h10></label>
                                    <input type="number" class="form-control" name="min_players" id="name" required="required"
                                           value="{{$gameRule->min_players}}"/>
                                </div><br>

                                <div class="form-group1">
                                    <label for="name"><h10>Max Rounds:</h10></label>
                                    <input type="number" class="form-control" name="max_rounds" id="name" required="required"
                                           value="{{$gameRule->max_rounds}}"/>
                                </div><br>

                                <div class="form-group1">
                                    <label for="name"><h10>Amount of player for the Knockout Phase:</h10></label>
                                    <input type="number" class="form-control" name="knockout_phase" id="name" required="required"
                                           value="{{$gameRule->knockout_phase}}"/>
                                </div><br>

                                <button type="submit" class="btn btn-primary float-right">Update</button>
                            </form>
                                <a href="{{route('game.overview', ['game' => $game->id])}}" class="btn btn-primary float-left" role="button">Back</a>
                        </div>
                    </div>
                </div>
                <div class="col-sm-2"></div>
            </div>
        </div>
        <div class="col-sm-1"></div>
    </div>
    </div>
@endsection

resources/views/gamerules/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="row h-100">
        <div class="col-sm-2"></div>
        <div class="col-sm-8">
            <h1>Game Rules<a href="{{route('game.gamerules.create', ['game'=> $game->id])}}" class="btn btn-primary float-right" role="button">Add New Game Rules</a></h1><hr>
            <div class="row h-100">
                <div class="col-sm-12">
                    <div class="row">
                        <div class="col-sm-12">
                            {{$gamerules['id']}}

                            {{ $gamerules->game['name']}}

                            {{$gamerules['max_players']}}

                            {{$gamerules['min_players']}}

                            <form method='get' action="{{route('game.gamerules.edit', ['game' => $game->id, 'gamerule' => $gamerules->id])}}"
                                  style="display: inline-block; float: right">
                                @csrf
                                <button type="submit" class="btn btn-primary">Edit</button>
                            </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-2"></div>
    </div>
@endsection

resources/views/gamerules/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="row h-100">
        <div class="col-sm-4"></div>
        <div class="col-sm-4">
            <h1>Game Rule</h1><hr>
            <div class="row h-100">
                <div class="col-sm-12">
                    <div class="row">
                        <div class="card">
                            <div class="card-header">
                                Game Rule ID:
                                {{ $gamerule->id }}
                            </div>
                            <div class="card-body">
                                Game Name:
                                {{ $gamerule->game['name']}}<br>
                                Max Players:
                                {{$gamerule['max_players']}}<br>
                                Min Players:
                                {{$gamerule['min_players']}}<br>
                                Max Rounds:
                                {{$gamerule['max_rounds']}}<br>
                                Amount of player for the Knockout Phase:
                                {{$gamerule['knockout_phase']}}<br>
                                User ID:
                                {{$gamerule['user_id']}}<br>
                                Created:
                                {{$gamerule['created_at']}}<br>
                                Updated:
                                {{$gamerule['updated_at']}}<br>
                            </div>
                        </div>
                    </div><br>
                    <a href="{{route('gamerules.index')}}" class="btn btn-primary float-left" role="button">Back</a>
                </div>
            </div>
        </div>
        <div class="col-sm-4"></div>
    </div>
@endsection