routes/web.php
<?php

use App\Http\Controllers\AdminController;
use App\Http\Controllers\GameRulesController;
use App\Http\Controllers\ScoresController;
use Illuminate\Support\Facades\Route;

Auth::routes();

Route::get('/players/{game}', 'PlayerController@showPlayers')->name('showPlayers');

//home
Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');
Route::get('/', 'HomeController@index')->name('home')->middleware('auth');

//clock
Route::get('/clock', 'ClockController@showClock')->middleware('auth');
Route::get('/clock/{round_id}', 'ClockController@showClock')->name('showClock')->middleware('auth');


//knockout
//Route::resource('knockout', 'KnockoutController');
Route::get('/game/{game}/knockout/{round}', 'KnockoutController@getKnockoutPlayers')->name('getKnockoutPlayers')->middleware('auth');
//Route::get('/game/{game}/knockout/{round}', 'KnockoutController@getKnockoutPlayers')->name('getKnockoutPlayers')->middleware('auth');
Route::post('/game/{game}/knockout/{round}', 'KnockoutController@storeKnockoutPlayers')->name('storeKnockoutPlayers')->middleware('auth');

//players
Route::resource('game.player', 'PlayerController');
Route::get('player.loginPlayer', 'PlayerController@login')->name('game.player.login');
Route::get('player.gamePlayer', 'PlayerController@selectGame')->name('selectGame');

//rounds
Route::resource('rounds', 'RoundsController')->middleware('auth');
Route::get('/store_round', 'RoundsController@storeRoundForm')->middleware('auth');
route::get('getOneRound/{round}', 'RoundsController@getOneRound')->middleware('auth');
Route::get('/game/{game}/rounds', 'RoundsController@showRounds')->name('showRounds')->middleware('auth');
Route::post('/game/{game}/round', 'RoundsController@storeRound')->name('storeRound')->middleware('auth');
Route::post('/game/{game}/knockout', 'RoundsController@storeKnockoutRound')->name('storeKnockoutRound')->middleware('auth');

//games
Route::resource('game', 'GameController')->middleware('auth');
Route::get('/gameoverview', 'HomeController@index')->middleware('auth');
Route::get('/game/{game}/overview', 'GameController@overview')->name('game.overview')->middleware('auth');

//tables
Route::resource('tables', 'TablesController')->middleware('auth');
Route::get('tables/{table}/player/{player}', 'TablesController@deletePlayer')->name('deletePlayer')->middleware('auth');
Route::get('/admin_tafels_overview', 'AdminController@showAdminTafelsOverview')->middleware('auth');
Route::get('/admin_tafel_toevoegen', 'AdminController@showAdminTafelToevoegen')->middleware('auth');
Route::get('game/{game}/round/{round}/tables', 'TablesController@showTables')->name('showTables')->middleware('auth');
Route::post('/game/{game}/round/{round}/tables', 'TablesController@storeTable')->name('storeTable')->middleware('auth');
Route::get('/game/{game}/tables', 'TablesController@getGameTables')->name('game.tables')->middleware('auth');
Route::post('/game/{game}/table', 'TablesController@store')->name('game.table.store')->middleware('auth');

//scores
Route::resource('scores', 'ScoresController')->middleware('auth');
Route::get('gameScores/{id}', 'ScoresController@showGameScore')->middleware('auth');
Route::get('score/{id}', 'ScoresController@showPlayerScore')->name('showPlayerScore')->middleware('auth');
Route::get('game/{game}/score', 'ScoresController@scoresOverview')->name('scoresOverview')->middleware('auth');
Route::post('/game/{game}/round/{round}/score', 'ScoresController@storeScore')->name('storeScore')->middleware('auth');
Route::post('/player/{game}', 'PlayerController@storePlayer')->name('storePlayer');


//player home


//player scores
Route::get('/player_score', 'ScoresController@showFindPlayerScore')->name('showFindPLayerScore');
Route::post('/player_score', 'ScoresController@findPlayerScore')->name('findPlayerScore');

//GameRules
Route::resource('game.gamerules', 'GameRulesController')->middleware('auth');
Route::get('/gamerule_delete/{gamerule}', 'GameRulesController@destroy')->name('deleteGameRules')->middleware('auth');

//Admin
Route::get('/adminlogin', 'HomeController@adminLogin')->name('adminLogin');

Route::post('/playerLogin', 'PlayerController@login')->name('playerLogin');

app/Game.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasOne;

class Game extends Model
{
    /**
     * @return HasOne
     */
    public function gameRules()
    {
        return $this->hasOne(GameRule::class);
    }

    /**
     * @return HasMany
     */
    public function playerGames()
    {
        return $this->hasMany(Player_games::class);
    }

    /**
     * @return HasMany
     */
    public function tables()
    {
        return $this->hasMany(Table::class);
    }

    /**
     * @return HasMany
     */
    Public function rounds()
    {
        return $this->hasMany(Round::class);
    }

    /**
     * @return BelongsToMany
     */
    public function players()
    {
        return $this->belongsToMany(Player::class, 'player_games')->withPivot('weight', 'leaderboard_points');
    }

}

app/Http/Controllers/GameController.php
<?php

namespace App\Http\Controllers;

use App\Game;
use App\Http\Requests\UpdateGameRequest;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Redirector;
use Illuminate\View\View;

class GameController extends Controller
{
    /**
     * @return Factory|View
     */
    public function index()
    {
        $games = Game::all();
        return view('game.game', compact('games'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return RedirectResponse
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     * @param Request $request
     *
     * @return RedirectResponse|Redirector
     */
    public function store(Request $request)
    {
        $game = new Game;
        $game->name = $request->get('name');
        $game->description = $request->get('description');
        $game->user_id = $request->user()->id;
        $game->save();
        return redirect()->route('game.gamerules.create', ['game' => $game->id])->with('success','Game created successfully!');
    }

    /**
     * Display the specified resource.
     * @param Game $game
     *
     * @return Factory|View
     */
    public function show(Game $game)
    {
        $game = Game::all()->where('id', $game);
        return view('game', ['game'=>$game]);
    }

    /**
     * Show the form for editing the specified resource.
     * @param Game $game
     *
     * @return Factory|View
     */
    public function edit(Game $game)
    {
        return view('game.edit', ['game'=>$game]);
    }

    /**
     * @param UpdateGameRequest $request
     * @param Game $game
     *
     * @return RedirectResponse
     */
    public function update(UpdateGameRequest $request, Game $game)
    {
        $game->name = $request->get('name');
        $game->description = $request->get('description');
        $game->save();

        $games = Game::all();
        return back()->with('info','Game updated successfully!');
    }

    /**
     * Remove the specified resource from storage.
     * @param Game $game
     * @return RedirectResponse
     *
     * @throws \Exception
     */
    public function destroy(Game $game)
    {
        $game->delete();

        return back()->with('warning','Game deleted successfully!');
    }

    /**
     * @param Game $game
     * @return Factory|View
     */
    public function overview(Game $game)
    {
        return view('gameOverview', compact('game'));
    }
}

resources/views/game/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="modal-body">
        <form action="{{route('game.update', [$game->id])}}" method="post">
            @csrf
            {{method_field('PUT')}}
            <input type="string" name="name" value="{{$game->name}}">
            <input type="text" name="description" value="{{$game->description}}">
            <button class="btn btn-primary" type="submit" name="submit">submit</button>
        </form>
    </div>
    <a href="{{route('game.index')}}"> <button class="btn btn-primary" type="submit" name="submit">return</button></a>
@endsection

resources/views/game/game.blade.php
@extends ('layouts.app')

@section('content')
    @include('components.modalCreateGame')
    <div class="row">
        <div class="col-sm-2">
        </div>
        <div class="col-sm-8">
            <h1>Overzicht spellen</h1>
            <button type="button" class="btn btn-secondary float-right m-3 shadow" data-toggle="modal"
                    data-target="#modalCreateGame">Voeg een spel toe
            </button>
        </div>
        <div class="col-sm-2"></div>
        <div class="col-sm-2"></div>
        <div class="col-sm-8">
            <div class="container border-left border-right border-top border-bottom rounded p5 bg-waring shadow">
                @foreach($games as $game)
                    <div class="card m-3 shadow-lg p-4 mb-4 bg-white">
                        <div class="card-header shadow">{{$game['name']}}</div>
                        <div class="card-body">
                            <p class="card-text">{{$game['description']}}</p>
                            <div class="btn-group float-left">
                                <form method="get" action="{{route('showRounds', [$game->id])}}">
                                    @csrf
                                    <button type="submit" class="btn btn-primary shadow mr-3">rounds</button>
                                </form>
                                <form method="get" action="{{route('getKnockoutPlayers', [$game->id])}}">
                                    @csrf
                                    <button type="submit" class="btn btn-primary shadow">knockout</button>
                                </form>
                                <form method="get" action="{{route('showPlayers', [$game->id])}}">
                                    @csrf
                                    <button type="submit" class="btn btn-primary shadow">players</button>
                                </form>
                            </div>
                            <div class="btn-group float-right">
                                <form method="get" action="{{route('game.edit', [$game->id])}}">
                                    @csrf
                                    <button type="submit" class="btn btn-primary shadow">pas aan</button>
                                </form>
                                <form method="post" action="{{route('game.destroy', [$game->id])}}">
                                    @csrf
                                    {{method_field('DELETE')}}
                                    <button type="submit" class="btn btn-danger shadow">verwijder</button>
                                </form>
                            </div>
                        </div>
                    </div>
                @endforeach
            </div>
        </div>
        <div class="col-sm-2"></div>
    </div>
@endsection

resources/views/game/gameOverview.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            @foreach($players as $player)
            <div class="col-md-8">
                <a href="/player/{{$player->id}}">{{$player->first_name}} {{$player->last_name}}</a>
                <a href="{{route('showPlayerScore', ['id' => $player->id])}}">playersccore</a>
                <form method="get" action="{{route('showPlayerScore', ['player' => $player->id])}}">
                    @csrf
                    <input type="submit" class="btn-warning" value="Add score">
                </form>
            </div>
            @endforeach
        </div>
    </div>
@endsection