routes/web.php
<?php

use App\Http\Controllers\AdminController;
use App\Http\Controllers\GameRulesController;
use App\Http\Controllers\ScoresController;
use Illuminate\Support\Facades\Route;

Auth::routes();

Route::get('/players/{game}', 'PlayerController@showPlayers')->name('showPlayers');

//home
Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');
Route::get('/', 'HomeController@index')->name('home')->middleware('auth');

//clock
Route::get('/clock', 'ClockController@showClock')->middleware('auth');
Route::get('/clock/{round_id}', 'ClockController@showClock')->name('showClock')->middleware('auth');


//knockout
//Route::resource('knockout', 'KnockoutController');
Route::get('/game/{game}/knockout/{round}', 'KnockoutController@getKnockoutPlayers')->name('getKnockoutPlayers')->middleware('auth');
//Route::get('/game/{game}/knockout/{round}', 'KnockoutController@getKnockoutPlayers')->name('getKnockoutPlayers')->middleware('auth');
Route::post('/game/{game}/knockout/{round}', 'KnockoutController@storeKnockoutPlayers')->name('storeKnockoutPlayers')->middleware('auth');

//players
Route::resource('game.player', 'PlayerController');
Route::get('player.loginPlayer', 'PlayerController@login')->name('game.player.login');
Route::get('player.gamePlayer', 'PlayerController@selectGame')->name('selectGame');

//rounds
Route::resource('rounds', 'RoundsController')->middleware('auth');
Route::get('/store_round', 'RoundsController@storeRoundForm')->middleware('auth');
route::get('getOneRound/{round}', 'RoundsController@getOneRound')->middleware('auth');
Route::get('/game/{game}/rounds', 'RoundsController@showRounds')->name('showRounds')->middleware('auth');
Route::post('/game/{game}/round', 'RoundsController@storeRound')->name('storeRound')->middleware('auth');
Route::post('/game/{game}/knockout', 'RoundsController@storeKnockoutRound')->name('storeKnockoutRound')->middleware('auth');

//games
Route::resource('game', 'GameController')->middleware('auth');
Route::get('/gameoverview', 'HomeController@index')->middleware('auth');
Route::get('/game/{game}/overview', 'GameController@overview')->name('game.overview')->middleware('auth');

//tables
Route::resource('tables', 'TablesController')->middleware('auth');
Route::get('tables/{table}/player/{player}', 'TablesController@deletePlayer')->name('deletePlayer')->middleware('auth');
Route::get('/admin_tafels_overview', 'AdminController@showAdminTafelsOverview')->middleware('auth');
Route::get('/admin_tafel_toevoegen', 'AdminController@showAdminTafelToevoegen')->middleware('auth');
Route::get('game/{game}/round/{round}/tables', 'TablesController@showTables')->name('showTables')->middleware('auth');
Route::post('/game/{game}/round/{round}/tables', 'TablesController@storeTable')->name('storeTable')->middleware('auth');
Route::get('/game/{game}/tables', 'TablesController@getGameTables')->name('game.tables')->middleware('auth');
Route::post('/game/{game}/table', 'TablesController@store')->name('game.table.store')->middleware('auth');

//scores
Route::resource('scores', 'ScoresController')->middleware('auth');
Route::get('gameScores/{id}', 'ScoresController@showGameScore')->middleware('auth');
Route::get('score/{id}', 'ScoresController@showPlayerScore')->name('showPlayerScore')->middleware('auth');
Route::get('game/{game}/score', 'ScoresController@scoresOverview')->name('scoresOverview')->middleware('auth');
Route::post('/game/{game}/round/{round}/score', 'ScoresController@storeScore')->name('storeScore')->middleware('auth');
Route::post('/player/{game}', 'PlayerController@storePlayer')->name('storePlayer');


//player home


//player scores
Route::get('/player_score', 'ScoresController@showFindPlayerScore')->name('showFindPLayerScore');
Route::post('/player_score', 'ScoresController@findPlayerScore')->name('findPlayerScore');

//GameRules
Route::resource('game.gamerules', 'GameRulesController')->middleware('auth');
Route::get('/gamerule_delete/{gamerule}', 'GameRulesController@destroy')->name('deleteGameRules')->middleware('auth');

//Admin
Route::get('/adminlogin', 'HomeController@adminLogin')->name('adminLogin');

Route::post('/playerLogin', 'PlayerController@login')->name('playerLogin');

app/Player.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Player extends Model
{
    /**
     * @return BelongsToMany
     */
    public function tables()
    {
        return $this->belongsToMany(Table::class, "table_players");
    }

    /**
     * @return HasMany
     */
    public function scores()
    {
        return $this->hasMany(Score::class);
    }

    /**
     * @return BelongsToMany
     */
    public function games()
    {
        return $this->belongsToMany(Game::class, 'player_games');
    }
}

app/Http/Controllers/PlayerController.php
<?php

namespace App\Http\Controllers;

use App\Events\OrderShiped;
use App\Game;
use App\GameRule;
use App\Http\Requests\CreatePlayerRequest;
use App\player;
use App\Score;
use App\Round;
use http\Client\Curl\User;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Routing\Redirector;
use Illuminate\Support\Str;
use Illuminate\View\View;


class PlayerController extends Controller
{
    /**
     * @param Game $game
     *
     * @return Factory|View
     */
    public function index(Game $game)
    {
        $players = $game->players()->Paginate(20);
        $rounds = Round::where('game_id', '=', $game->id)->get();
        $scores = Score::all();
        return view('player.playersOverview', compact('game', 'players', 'rounds', 'scores'));
    }

    /**
     * @param Request $request
     * @param Game $game
     * @param player $player
     *
     * @return Factory|View
     */
    public function login(Request $request, Game $game, player $player)
    {

        $players = Player::all();
        foreach ($players as $player){
            if ($player->code == $request->Code && $player->email == $request->email) {
                $player->checked_in = 1;
                $player->save();

                return view('/confirmation', compact('players'))->with('msg','Player checked in successfully!');
            }
        }
        return view('/confirmation', compact('players'))->with('msg','Player check in failed!');
    }

    /**
     * @param Game $game
     *
     * @return Factory|View
     */
    public function create(Game $game)
    {
        return view('player.createPlayer', compact('game'));
    }

    /**
     * @param Request $request
     * @param Game $game
     */
    public function store(Request $request, Game $game)
    {
        //
    }

    /**
     * @param CreatePlayerRequest $request
     * @param Game $game
     *
     * @return Factory|View
     */
    public function storePlayer(CreatePlayerRequest $request, Game $game)
    {
        $gameRules = GameRule::where('id', $game->id)->first();
        if (count($game->players()->get()) < $gameRules['max_players']) {
            $player = new Player;
            $player->first_name = $request->get('first_name');
            $player->last_name = $request->get('last_name');
            $player->code = Str::random(6);
            $player->email = $request->get('email');
            $player->phonenumber = $request->get('phonenumber');
            $player->checked_in = false;
            $player->state = false;
            $player->user_id = 1;
            $player->save();
            $player->games()->attach($game->id);

            event(new OrderShiped($player));

            return view('/confirmation')->with('msg','Player added successfully!');

        }
        return view('/confirmation')->with('msg','Player limit reached!');

    }

    /**
     * @param Game $game
     *
     * @return Factory|View
     */
    public function showPlayers(Game $game)
    {
        $players = $game->players()->get();
        return view('game.gameOverview', compact('players'));
    }


    /**
     * @param player $player
     *
     * @return Factory|View
     */
    public function show(player $player)
    {
        $scores = $player->scores()->get();
        return view('player.playerOverview', compact('scores', 'player'));
    }

    /**
     * @param Game $game
     * @param player $player
     *
     * @return Factory|View
     */
    public function edit(Game $game, player $player)
    {
        return view('player.playerupdate', compact('player', 'game'));
    }

    /**
     * @param Request $request
     * @param Game $game
     * @param player $player
     *
     * @return RedirectResponse|Redirector
     */
    public function update(Request $request, Game $game, player $player)
    {
        $player->first_name = $request->get('first_name');
        $player->last_name = $request->get('last_name');
        $player->email = $request->get('email');
        $player->phonenumber = $request->get('phonenumber');
        $player->save();
        $players = $game->players()->get();

        return redirect('/game/'.$game->id.'/player')->with(compact('players', 'player', 'game'))
            ->with('info','Player updated successfully!');
    }

    /**
     * @param Game $game
     * @param player $player
     *
     * @return Factory|View
     * @throws \Exception
     */
    public function destroy(Game $game, player $player)
    {
        $player->delete();
        $players = $game->players()->get();
        return view('player.playersOverview', compact('players', 'game'))->with('warning','Player deleted successfully!');
    }

    /**
     * @param Game $game
     *
     * @return Factory|View
     */
    public function selectGame(Game $game)
    {
        $games = Game::all();
        return view('player.gamePlayer', compact('games'));
    }
}

resources/views/player/createPlayer.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-sm-1"></div>
                <div class="col-md-8" style="margin: 3%">
                    <h1>New Players Sign Up Form</h1><hr>
                    <form method="post" action="{{route('storePlayer', [$game->id])}}">
                        @csrf
                        <div class="modal-body">
                            <input name="first_name" type="text" class="form-control mt-2" placeholder="First name"
                                   required="required"/>
                            <input name="last_name" type="text" class="form-control mt-2" placeholder="Last name"
                                   required="required"/>
                            <input name="email" type="email" class="form-control mt-2" placeholder="Email"
                                   required="required"/>
                            <input name="phonenumber" type="number" class="form-control mt-2" placeholder="Phonenumber"
                                   required="required"/>
                        </div>
                        <div class="modal-footer">
                            <a href="{{ URL::previous() }}" class="btn btn-primary float-left" role="button">Back</a>
                            <input type="submit" class="btn-warning" value="Confirm">
                        </div>
                    </form>
                </div>
            <div class="col-sm-1"></div>
        </div>
    </div>
@endsection

resources/views/player/gamePlayer.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8">
                <h1 class="text-center">Choose a game to sign up</h1><hr>
                <div class="row h-100">
                    @foreach($games as $game)
                        <div class="col-md-4">
                            <div class="card w-100">
                                <div class="card-body">
                                    <h3>{{$game->name}}</h3>
                                    <hr>
                                    <p class="card-text">{{$game->description}}</p>
                                    <a href="{{route('game.player.create', ['game' => $game->id])}}" class="btn btn-primary">Choose Game</a>
                                </div>
                            </div>
                        </div>
                    @endforeach
                </div>
            </div>
            <div class="col-md-2"></div>
        </div>
    </div>
@endsection

resources/views/player/playerHome.blade.php
@extends('layouts.app')

@section('content')
    <div class="row h-100">
        <div class="col-sm-2"></div>
        <div class="col-sm-6">
            <h1 style="text-align: center;">Home Page Crew
                <a href="{{route('home')}}" class="btn btn-primary float-left" role="button">Back</a>
            </h1><hr>
            <div class="row">
                <div class="row h-100">
                    <div class="col-sm-12">
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="card m-5 text-center card-hover" style="height: 4rem; background-color: #e3342f">
                                    <div class="card-body">
                                        <h5 style="color: white"><p>ROUNDS</h5>
                                        <a href="{{route('game.gamerules.edit', ['game' => $game->id, 'gamerule' => $game->gamerules()->first()->id])}}" class="stretched-link"></a>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="card m-5 text-center card-hover" style="height: 4rem; background-color: #e3342f">
                                    <div class="card-body">
                                        <h5 style="color: white"><p>SCORES</h5>
                                        <a href="{{route('game.player.index', ['game' => $game->id])}}" class="stretched-link"></a>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="card m-5 text-center card-hover" style="height: 4rem; background-color: #e3342f">
                                    <div class="card-body">
                                        <h5 style="color: white"><p>SCORE BOARD</h5>
                                        <a href="{{route('scoresOverview', ['game' => $game->id])}}" class="stretched-link"></a>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="card m-5 text-center card-hover" style="height: 4rem; background-color: #e3342f">
                                    <div class="card-body">
                                        <h5 style="color: white"><p>ROUNDS</h5>
                                        <a href="{{route('showRounds', ['game' => $game->id])}}" class="stretched-link"></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-3">
            <img src="{{URL::asset('/images/Carcassonne.jpg')}}" alt="logo">
        </div>
        <div class="col-sm-1"></div>
    </div>
@endsection

resources/views/player/playerOverview.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <h1 class="mt-3">Scores</h1>
                <div class="row h-100">
                    @foreach($scores as $score)
                       <div class="col-md-8">
                           Points: {{$score->points}}
                       </div>
                       <div class="col-md-8">
                           Weight: {{$score->weight}}
                       </div>
                        <form method="get" action="{{route('scores.edit', [$score->id])}}">
                           @csrf
                           <input type="submit" class="btn btn-warning" value="update">
                       </form>
                        <form method="post" action="{{route('scores.destroy', [$score->id])}}">
                            @csrf
                            {{method_field('DELETE')}}
                            <input type="submit" class="btn btn-danger" value="delete" style="margin-left: 5px">
                        </form>
                    @endforeach
                </div>
            </div>
            <div class="col-md-8" style="margin: 3%">
            <h1 class="mt-3">Details</h1>
                <div class="col-md-8 mt-3">
                    First name: {{$player->first_name}}
                </div>
                <div class="col-md-8">
                    Last name: {{$player->last_name}}
                </div>
                <div class="col-md-8">
                    Code: {{$player->code}}
                </div>
                <div class="col-md-8">
                    Phonenumber: {{$player->phonenumber}}
                </div>
                <div class="col-md-8">
                    Email: {{$player->email}}
                </div>
                <form method="get" action="{{route('player.edit', [$player->id])}}">
                    @csrf
                    <input type="submit" class="btn btn-warning" value="update">
                </form>
                <form method="post" action="{{route('player.destroy', [$player->id])}}">
                    @csrf
                    {{method_field('DELETE')}}
                    <input type="submit" class="btn btn-danger" value="delete" style="margin-left: 5px">
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/player/playersOverview.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-9">
                <h1>Players Overview<a class="btn btn-primary btn float-right" href="{{route('game.player.create', ['game' => $game->id])}}">Create</a></h1><hr>
                <div class="col-sm-12">
                    <div class="row">
                        <div class="col-sm-2">
                            First Name
                        </div>
                        <div class="col-sm-2">
                            Last Name
                        </div>
                        <div class="col-sm-1">
                            Code
                        </div>
                        <div class="col-sm-2">
                            Phonenummer
                        </div>
                        <div class="col-sm-2">
                            E-mail
                        </div>
                        <div class="col-sm-1">

                        </div>
                        <div class="col-sm-1">

                        </div>
                        <div class="col-sm-1">

                        </div>
                    </div><hr>
                    <div class="row">
                        @foreach($players as $player)

                            <div class="col-sm-2">
                                {{$player->first_name}}
                            </div>
                            <div class="col-sm-2">
                                {{$player->last_name}}
                            </div>
                            <div class="col-sm-1">
                                {{$player->code}}
                            </div>
                            <div class="col-sm-2">
                                {{$player->phonenumber}}
                            </div>
                            <div class="col-sm-2">
                                {{$player->email}}
                            </div>
                            <div class="col-1">
                                <button
                                    {{--data-path="{{ route('playerScore',[$player->id]) }}"--}}
                                    type="button" class="btn btn-secondary" data-toggle="modal"
                                    data-target="#modalPlayerScores">Scores
                                </button>
                            </div>
                            <div class="col-sm-1">
                                <form method="get" action="{{route('game.player.edit', ['game' => $game->id, 'player' => $player->id])}}">
                                    @csrf
                                    <input type="submit" class="btn btn-warning" value="Update">
                                </form>
                            </div>
                            <div class="col-sm-1">
                                <form method="post" action="{{route('game.player.destroy', ['game' => $game->id, 'player' => $player->id])}}">
                                    @csrf
                                    {{method_field('DELETE')}}
                                    <input type="submit" class="btn btn-danger" value="Delete" style="margin-left: 5px">
                                </form>

                            </div><div class="col-sm-12"><hr></div><br><br>
                            <!-- The Modal -->
                            <div class="modal" id="modalPlayerScores">
                                <div class="modal-dialog">
                                    <div class="modal-content">

                                        <!-- Modal Header -->
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                                        </div>
                                        <!-- Modal body -->
                                        <div class="modal-body">
                                            @foreach($rounds as $round)
                                                <hr>
                                                Round: {{$round->name}}
                                                <br>
                                                Game:{{$game->id}}

                                                @foreach($scores as $score)
                                                    @if($score->player_id === $player->id && $score->round_id === $round->id)
                                                        weight: {{$score->weight}}
                                                        <br>
                                                        points: {{$score->points}}
                                                    @endif
                                                @endforeach

                                            @endforeach

                                        </div>

                                        <!-- Modal footer -->
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                                        </div>

                                    </div>
                                </div>
                            </div>
                        @endforeach
                            {{ $players->links() }}
                    </div>
                    <a href="{{route('game.overview', ['game' => $game->id])}}" class="btn btn-primary float-left" role="button">Back</a>
                </div>
            </div>
            <div class="col-md-1"></div>
        </div>
    </div>
@endsection

resources/views/player/playerupdate.blade.php
@extends('layouts.app')

@section('content')

    <div class="row h-100">
        <div class="col-sm-2"></div>
        <div class="col-sm-8">
            <h1 style="text-align: center;">Player Edit</h1><hr>
                    <form method="post" action="{{route('game.player.update', ['game' => $game->id, 'player' => $player->id])}}">
                        @csrf
                        @method('PUT')
                        <div class="modal-body">
                            <input name="first_name" type="text" class="form-control mt-2" placeholder="First name"
                                   value="{{$player->first_name}}" required="required"/>
                            <input name="last_name" type="text" class="form-control mt-2" placeholder="Last name"
                                   value="{{$player->last_name}}" required="required"/>
                            <input name="email" type="email" class="form-control mt-2" placeholder="Email"
                                   value="{{$player->email}}" required="required"/>
                            <input name="phonenumber" type="number" class="form-control mt-2" placeholder="Phonenumber"
                                   value="{{$player->phonenumber}}" required="required"/>
                        </div>
                        <div class="modal-footer">
                            <a href="{{ URL::previous() }}" class="btn btn-primary float-left" role="button">Back</a>
                            <input type="submit" class="btn-warning" value="Update">
                        </div>
                    </form>

            </div>
        </div>
        <div class="col-sm-2"></div>
    </div>
@endsection